const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const P=require('../push-core.js'),C=require('../sync-core.js');
const data=new Map(),fields={},requests=[],states=[];
const context={console,crypto,TextEncoder,TextDecoder,URL,Response,AbortController,setTimeout,clearTimeout,setInterval,clearInterval,Date,Promise,HierroPushCore:P,HierroSyncCore:C,
 localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)},
 document:{visibilityState:'hidden',querySelectorAll:()=>[],addEventListener(){},getElementById:id=>fields[id]||=( {innerHTML:'',style:{},value:''} )},
 navigator:{onLine:true,serviceWorker:{controller:{postMessage:m=>states.push(m)}}},Notification:{permission:'granted'},location:{hash:'',pathname:'/'},
 fetch:async(url,options)=>{requests.push({url,input:JSON.parse(options.body)});return new Response(JSON.stringify({accepted:true}),{status:200});}};
context.window=context;vm.createContext(context);
const engine=fs.readFileSync('index.html','utf8').match(/<script>([\s\S]*)<\/script>/)[1].replace(/\(function init\(\)\{[\s\S]*?\}\)\(\);/,'');
vm.runInContext(['sync.js','push.js','ui.js'].map(f=>fs.readFileSync(f,'utf8')).join('\n')+'\n'+engine,context);
const run=s=>vm.runInContext(s,context);let count=0;const ok=(v,m)=>{assert.ok(v,m);count++;console.log('OK '+m);};
(async()=>{
 const receiver=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);
 context.subscription={keys:{p256dh:P.b64(await crypto.subtle.exportKey('raw',receiver.publicKey)),auth:P.b64(crypto.getRandomValues(new Uint8Array(16)))}};
 run(`render=()=>{};go=v=>{view=v};window.scrollTo=()=>{};
 db.settings.goal='hipertrofia';db.settings.unit='kg';
 db.routines=[{id:'qa-day',name:'Torso',exercises:[{key:'qa-tower',name:'Jalón'}]}];
 Object.assign(exMeta('qa-tower'),{type:'normal',equip:'placas',stack:{unit:'lb',start:2.5,step:5,extra:1.5,extraMax:3},cap:250*.45359237});
 startSession('qa-day');db.active.exercises[0].warmupDone=true;
 db.active.exercises[0].sets=[{w:'65.5',r:'6',done:true,totalKg:65.5*.45359237},{w:'',r:'',done:false}];
 db.active.exercises[0].sugg={w:65.5*.45359237,reps:6};
 db.active.lastSeriesAt=Date.now();db.active.restUntil=Date.now()+60000;db.active.uiRest=true;
 hierroSync={keys:{id:'qa-vault',auth:'qa'},state:{created:true,revision:3},status:'synced',emit:()=>{}};syncDevice='qa-phone';
 pushPrefs={enabled:true,rest:true,idle:true,details:true,seq:0,vault:'qa-vault'};pushRegistered=true;pushSub={toJSON:()=>subscription};
 save();pushReady=true;`);
 const copy=run('pushSnapshot().rest.next.body');
 ok(copy.includes('Placa 13')&&copy.includes('ajuste fino 3 lb'),'el aviso usa placa y ajuste fino reales de la máquina en libras');
 ok(copy.includes('65,5 lb')&&copy.includes('6 reps'),'la carga mantiene la unidad de la torre aunque el gimnasio esté en kilos');
 run('db.active.localOnly=true');ok(run('pushSnapshot()')===null,'una sesión independiente no programa avisos para la sesión de otro dispositivo');run('delete db.active.localOnly');
 run(`db.active.exercises[0].warmup={phase:'set',completed:0,plan:{steps:[{w:10,reps:8},{w:20,reps:5}]}};`);
 ok(run('pushSnapshot().next.body').startsWith('Calentamiento'),'el recordatorio muestra el calentamiento pendiente y no la carga de trabajo');
 run(`db.active.exercises[0].warmup.phase='rest';db.active.exercises[0].warmup.completed=1;db.active.exercises[0].warmup.restUntil=Date.now()+30000;`);
 ok(run('pushSnapshot().rest.kind')==='warmup'&&run('pushSnapshot().rest.next.body').includes('5 reps'),'el descanso de calentamiento anuncia su siguiente aproximación');
 run('db.active.exercises[0].warmup.completed=2');
 ok(!run('pushSnapshot().rest.next.body').startsWith('Calentamiento'),'al terminar las aproximaciones anuncia las series de trabajo');
 run(`db.active.exercises[0].warmup.phase='setup';`);
 ok(run('pushSnapshot().next.body').includes('elegir tu carga'),'si falta una carga de referencia invita a prepararla sin inventar un peso');
 run('delete db.active.exercises[0].warmup;save()');
 const savedWorkout=run('JSON.stringify(db.active)');
 await run('pushChanged(true)');for(let i=0;i<30&&!requests.length;i++)await new Promise(r=>setTimeout(r,10));
 ok(requests.length===1&&requests[0].input.events.length===2,'guardar programa descanso e inactividad sin registrar ninguna serie extra');
 ok(requests[0].input.events.every(e=>!e.body.includes('Placa')),'ninguna carga en claro llega a la API desde el adaptador');
 run('db.active.restLastCue="cue";save();');await run('pushFlush()');
 ok(requests.length===1,'los ticks del reloj no generan nuevas solicitudes');
 run('db.active.restUntil+=30000;save();');await run('pushFlush()');
 ok(requests.length===2&&requests[1].input.seq>requests[0].input.seq,'ampliar descanso envía una nueva revisión del aviso');
 run('uiResetRest();save();');await run('pushFlush()');
 ok(requests.at(-1).input.events.length===1,'saltar descanso retira el aviso anterior y conserva el recordatorio opcional');
 run('db.active.lastLog=Date.now()+60000;save();');await run('pushFlush()');
 ok(requests.length===3,'escribir un borrador no reinicia los cinco minutos sin confirmar series');
 run('pushPrefs.details=false;pushFingerprint="";save();');await run('pushFlush()');
 ok(!run('HierroPushCore.schedule(pushSnapshot(),pushPrefs)[0].message.body').includes('Jalón'),'puede ocultar el ejercicio en la pantalla bloqueada');
 const previous=requests.length;
 run('navigator.onLine=false;db.active.restUntil=Date.now()+120000;save();');await run('pushFlush()');
 ok(requests.length===previous&&run('pushMessage').includes('Sin conexión'),'sin red conserva la sesión y explica que el aviso no está programado');
 run('navigator.onLine=true;pushChanged(true)');for(let i=0;i<30&&requests.length===previous;i++)await new Promise(r=>setTimeout(r,10));
 ok(requests.length===previous+1,'al reconectar envía el descanso pendiente');
 run('db.active=null;save();');await run('pushFlush()');
 ok(requests.at(-1).input.session===null&&!requests.at(-1).input.events.length,'terminar cancela en el servidor y en el service worker');
 ok(states.at(-1).state.session===null,'un push antiguo queda identificado como otra sesión');
 run('hierroSync.keys.id="other-vault";pushChanged(true)');await run('pushFlush()');
 ok(!states.at(-1).state.enabled,'cambiar de espacio no reutiliza los avisos del anterior');
 context.savedWorkout=savedWorkout;
 let releaseEncryption;const gate=new Promise(r=>releaseEncryption=r);
 context.HierroPushCore={...P,encrypt:async(...args)=>{await gate;return P.encrypt(...args);}};
 run('hierroSync.keys.id="qa-vault";db.active=JSON.parse(savedWorkout);pushPrefs.enabled=true;pushFingerprint="";save();pushChanged(true)');
 const beforeCancel=requests.length;
 run('pushPrefs.enabled=false;pushChanged(true)');releaseEncryption();
 for(let i=0;i<30&&run('pushRunning');i++)await new Promise(r=>setTimeout(r,10));
 ok(requests.length===beforeCancel&&!states.at(-1).state.enabled,'desactivar durante el cifrado impide que salga un plan nuevo');
 const events={};context.HierroPushCore=P;context.PushManager=class{};context.setInterval=()=>1;
 context.addEventListener=(name,fn)=>events[name]=fn;context.navigator.serviceWorker.addEventListener=()=>{};
 const registration={active:context.navigator.serviceWorker.controller,pushManager:{getSubscription:async()=>({endpoint:'https://web.push.apple.com/qa',toJSON:()=>context.subscription})}};
 context.navigator.serviceWorker.ready=Promise.resolve(registration);
 context.fetch=async(url,options={})=>{
  if(!context.navigator.onLine)throw Error('Offline');
  if(!options.body)return new Response(JSON.stringify({publicKey:'public'}));
  requests.push({url,input:JSON.parse(options.body)});return new Response(JSON.stringify({accepted:true,seq:0}));
 };
 run('pushPrefs.enabled=true;pushSavePrefs();pushRegistered=false;pushReg=null;pushSub=null;navigator.onLine=false;clearTimeout(pushTimer)');
 await run('pushInit()');
 ok(typeof events.online==='function'&&!run('pushRegistered'),'un arranque offline conserva el listener que reactivará los avisos');
 context.navigator.onLine=true;await events.online();
 for(let i=0;i<30&&run('pushRunning');i++)await new Promise(r=>setTimeout(r,10));
 ok(run('pushRegistered')&&requests.some(r=>r.url.endsWith('/push/register')),'al recuperar internet renueva la suscripción sin recargar la app');
 run('clearTimeout(pushTimer)');
 console.log(`PRUEBAS ADAPTADOR PUSH OK (${count})`);
})().catch(e=>{console.error(e);run('clearTimeout(pushTimer)');process.exitCode=1;});
