import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import C from '../sync-core.js';
import P from '../push-core.js';
const signing=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),jwk=await crypto.subtle.exportKey('jwk',signing.privateKey);
const modules=['worker','push-delivery','push-scheduler'].map(name=>({type:'ESModule',path:new URL('../sync-worker/'+name+'.mjs',import.meta.url).pathname.replace(/^\/(?=[A-Za-z]:)/,'')}));
let deliveries=[],replyStatus=201;
const mf=new Miniflare(convertV4MiniflareOptions({name:'push',modules,compatibilityDate:'2026-09-14',d1Databases:{DB:'push-test'},durableObjects:{PUSH:{className:'PushScheduler',useSQLite:true}},bindings:{ALLOWED_ORIGINS:'https://elrobamichis.github.io',VAPID_JWK:JSON.stringify(jwk)},outboundService:async request=>{deliveries.push({url:request.url,headers:Object.fromEntries(request.headers),body:await request.text()});return new Response(null,{status:replyStatus});}}));
let count=0;const ok=(v,m)=>{assert.ok(v,m);count++;console.log('OK '+m);};
try{
 const d=await mf.getD1Database('DB');for(const stmt of fs.readFileSync(new URL('../sync-worker/schema.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await d.prepare(stmt).run();
 const keys=await C.keys(await C.createKey()),packet=await C.seal(C.empty(),keys),base='https://app.test/v1/vaults/'+keys.id;
 const headers={Origin:'https://elrobamichis.github.io',Authorization:'Bearer '+keys.auth};
 const raw=(method,extra={})=>mf.dispatchFetch(base,{method,headers:{...headers,...extra},...(method==='POST'||method==='PUT'?{body:packet}:{})});
 await raw('POST',{'Content-Type':'application/octet-stream'});
 const device='phone-qa-1',other='desktop-qa-2';
 const call=(action,input={},customHeaders={})=>mf.dispatchFetch(base+'/push/'+action,{method:'POST',headers:{...headers,'Content-Type':'application/json',...customHeaders},body:JSON.stringify({device,...input})});
 const endpoint='https://web.push.apple.com/qa';
 ok((await mf.dispatchFetch('https://app.test/push/config',{headers:{Origin:headers.Origin}})).status===200,'publica la clave VAPID y admite Pages');
 ok((await call('register',{endpoint},{Authorization:'Bearer '+'a'.repeat(43)})).status===404,'registrar avisos requiere acceso al espacio');
 ok((await call('register',{endpoint:'https://localhost/private'})).status===400,'bloquea endpoints privados antes del envío');
 ok((await call('register',{device:'__proto__',endpoint})).status===400,'rechaza identificadores que alteren el prototipo del registro');
 ok((await call('register',{endpoint})).status===200,'registra el teléfono con su endpoint');
 await call('register',{device:other,endpoint});
 const receiver=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);
 const subscription={keys:{p256dh:P.b64(await crypto.subtle.exportKey('raw',receiver.publicKey)),auth:P.b64(crypto.getRandomValues(new Uint8Array(16)))}};
 const body=await P.encrypt(subscription,{v:1,title:'Descanso',body:'40 kg por lado'});
 const plan=(seq,at,id='rest-'+seq)=>({seq,revision:1,now:Date.now(),session:'workout',events:[{id,at,expires:at+90000,body}]});
 let at=Date.now()+60000;
 ok((await call('plan',plan(1,at))).status===200,'programa el descanso en Durable Objects');
 let state=await (await call('status')).json();ok(state.pending.length===1&&Math.abs(state.pending[0].at-at)<1000,'la alarma conserva la hora del contador');
 await call('plan',plan(3,at+30000,'extended'));await call('plan',plan(2,at,'old'));
 state=await (await call('status')).json();ok(state.pending[0].id==='extended','una solicitud atrasada no restaura el descanso anterior');
 ok((await call('plan',{...plan(1,at),device:other})).status===409,'otro dispositivo no roba los avisos con una revisión antigua');
 await raw('PUT',{'Content-Type':'application/octet-stream','If-Match':'"1"'});
 ok((await call('plan',{...plan(1,at,'transfer'),device:other,revision:2})).status===200,'la transferencia sincronizada mueve los avisos al nuevo dispositivo');
 ok((await call('plan',plan(4,at))).status===409,'el dueño anterior no vuelve a programar tras el traspaso');
 await call('plan',{device:other,seq:2,revision:2,now:Date.now(),session:null,events:[]});
 state=await (await call('status',{device:other})).json();ok(!state.pending.length,'terminar la sesión cancela todos sus avisos');
 // Real workerd alarms execute after the scheduling request has ended.
 const soon=Date.now()+150;
 await call('plan',{...plan(3,soon,'alarm-proof'),device:other,revision:2});
 for(let i=0;i<25&&!deliveries.length;i++)await new Promise(r=>setTimeout(r,100));
 ok(deliveries.length===1,'la alarma envía el push sin una página abierta ni peticiones nuevas');
 ok(deliveries[0].headers['content-encoding']==='aes128gcm'&&deliveries[0].headers.authorization.startsWith('vapid '),'envía el protocolo cifrado con identificación VAPID');
 ok(!deliveries[0].body.includes('40 kg'),'el envío al proveedor no revela los pesos');
 await call('plan',{...plan(4,Date.now()+100,'alarm-proof'),device:other,revision:2});
 await new Promise(r=>setTimeout(r,200));ok(deliveries.length===1,'no reenvía un aviso ya entregado al repetir su identificador');
 replyStatus=410;await call('plan',{...plan(5,Date.now()+100,'expired-sub'),device:other,revision:2});
 for(let i=0;i<25&&deliveries.length<2;i++)await new Promise(r=>setTimeout(r,100));
 state=await (await call('status',{device:other})).json();ok(!state.registered&&!state.pending.length,'una suscripción caducada se elimina y deja de generar intentos');
 await raw('DELETE',{'If-Match':'"2"'});ok((await call('status')).status===404,'eliminar el espacio también retira el programador');
 console.log(`PRUEBAS PUSH EN WORKER OK (${count})`);
}finally{await mf.dispose();}
