import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import C from '../sync-core.js';
const mf=new Miniflare(convertV4MiniflareOptions({name:'sync',modules:true,scriptPath:new URL('../sync-worker/worker.mjs',import.meta.url).pathname.replace(/^\/(?=[A-Za-z]:)/,''),compatibilityDate:'2026-09-14',d1Databases:{DB:'sync-test'},bindings:{ALLOWED_ORIGINS:'https://elrobamichis.github.io'}}));
let tests=0;
const ok=(v,m)=>{assert.ok(v,m);tests++;console.log('OK '+m);};
try{
 const d=await mf.getD1Database('DB');
 const schema=fs.readFileSync(new URL('../sync-worker/schema.sql',import.meta.url),'utf8');
 for(const stmt of schema.split(';').filter(s=>s.trim()))await d.prepare(stmt).run();
 const key=await C.keys(await C.createKey()),other=await C.keys(await C.createKey());
 const call=(method,k=key,body,revision,extra={})=>mf.dispatchFetch('https://sync.test/v1/vaults/'+k.id,{method,headers:{Origin:'https://elrobamichis.github.io',Authorization:'Bearer '+k.auth,...(body?{'Content-Type':'application/octet-stream'}:{}),...(revision?{'If-Match':'"'+revision+'"'}:{}),...extra},body});
 let r=await call('OPTIONS');ok(r.status===204&&r.headers.get('Access-Control-Allow-Origin')==='https://elrobamichis.github.io','preflight admite solo el origen configurado');
 r=await call('GET',key,undefined,undefined,{Origin:'https://other.example'});ok(r.status===403&&!r.headers.get('Access-Control-Allow-Origin'),'rechaza orígenes ajenos');
 r=await call('GET',key,undefined,undefined,{Authorization:''});ok(r.status===401,'no admite acceso sin credencial');
 const doc=C.empty(),packet=await C.seal(doc,key);
 r=await call('POST',key,packet);ok(r.status===201&&r.headers.get('ETag')==='"1"','crea la primera revisión en D1');
 r=await call('POST',key,packet);ok(r.status===409,'crear otra vez no reemplaza un espacio existente');
 r=await call('GET',{id:key.id,auth:other.auth});ok(r.status===404,'otra credencial no puede consultar el espacio');
 r=await call('GET');ok(C.equal(await C.open(await r.text(),key),doc)&&r.headers.get('Cache-Control')==='no-store','lee ciphertext completo sin caché');
 r=await call('GET',key,undefined,undefined,{'If-None-Match':'"1"'});ok(r.status===304,'no descarga de nuevo una copia sin cambios');
 r=await call('PUT',key,packet);ok(r.status===428,'cada escritura requiere una revisión conocida');
 const [one,two]=await Promise.all([call('PUT',key,packet,1),call('PUT',key,packet,1)]);
 ok([one.status,two.status].sort().join(',')==='204,409','D1 acepta una sola de dos escrituras concurrentes');
 const huge='h1.j.aaaaaaaaaaaaaaaa.'+'b'.repeat(2400000);
 r=await call('PUT',key,huge,2);ok(r.status===204,'divide una copia mayor que el límite de 2 MB por fila');
 r=await call('GET');ok((await r.text())===huge&&r.headers.get('ETag')==='"3"','recupera todos los fragmentos de la misma revisión');
 r=await call('PUT',key,packet,2);ok(r.status===409,'una escritura antigua no borra fragmentos actuales');
 r=await call('GET');ok((await r.text())===huge,'la revisión vigente permanece intacta después del rechazo');
 r=await call('PUT',{id:key.id,auth:other.auth},packet,3);ok(r.status===404,'verifica acceso antes de aceptar un cuerpo de escritura');
 r=await call('PUT',key,'texto sin cifrar',3);ok(r.status===400,'no acepta accidentalmente una copia JSON en claro');
 r=await call('PUT',key,packet,3,{'Content-Type':'text/plain'});ok(r.status===415,'exige el tipo de contenido del protocolo');
 r=await call('DELETE',key,undefined,2);ok(r.status===409,'borrar también comprueba la revisión');
 r=await call('DELETE',key,undefined,3);ok(r.status===204,'permite eliminar el espacio con su credencial');
 ok((await d.prepare('SELECT COUNT(*) AS n FROM chunks').first()).n===0,'el borrado retira también todos los fragmentos');
 ok((await call('GET')).status===404,'una cuenta eliminada ya no se puede leer');
 const stored=await d.prepare('PRAGMA table_info(vaults)').all();ok(!stored.results.some(x=>/key|token|data|name|email/.test(x.name)),'el servidor no tiene columnas para claves privadas o datos de entrenamiento');
 console.log(`\nTODAS LAS PRUEBAS D1 OK (${tests})`);
}finally{await mf.dispose();}
